// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiIMV8FMgY7kXe27vY2dfuCpGZ8A-MbZk',
    appId: '1:855952134775:web:b54a0d21d83e475077ec72',
    messagingSenderId: '855952134775',
    projectId: 'myfitnesscoach-ceb14',
    authDomain: 'myfitnesscoach-ceb14.firebaseapp.com',
    storageBucket: 'myfitnesscoach-ceb14.appspot.com',
    measurementId: 'G-G7JER5P1RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI_ZcEcGK8aJkwzR9Eg3Hfn4yir7RIkbY',
    appId: '1:855952134775:android:5c28a87b32de41b577ec72',
    messagingSenderId: '855952134775',
    projectId: 'myfitnesscoach-ceb14',
    storageBucket: 'myfitnesscoach-ceb14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBugiUggfjkVlcIZZOEilAofHVqoq8qKkA',
    appId: '1:855952134775:ios:5c0ee1df6d369a5877ec72',
    messagingSenderId: '855952134775',
    projectId: 'myfitnesscoach-ceb14',
    storageBucket: 'myfitnesscoach-ceb14.appspot.com',
    iosClientId: '855952134775-i81bi4iv1d07hnp1pnultbb8brtodtfk.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFitnessCoach',
  );
}
